/*
*   Action Types
*/

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';

export const LOAD_TRACKS_SUCCESS = 'LOAD_TRACKS_SUCCESS';
export const ADD_TRACK_TO_CART_SUCCESS = 'ADD_TRACK_TO_CART_SUCCESS';

export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
